export const employeesData = [
  {
    id: 1,
    name: "John Viky ",
    title: "HR Manager",
    salary: 4000,
    phone: "040-1234562",
    email: "johnviky@example.com",
    animal: "cat",
    startDate: "2015-04-27",
    location: "Helsinki",
    department: "Human Resources",
    skills: ["Recruiting", "Communication", "Employee Relations"],
  },
  {
    id: 2,
    name: "Mikko Laine",
    title: "Software Developer",
    salary: 5500,
    phone: "041-9876543",
    email: "mikko.laine@example.com",
    animal: "Dog",
    startDate: "2013-09-15",
    location: "Espoo",
    department: "IT",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: 3,
    name: "Liisa Mäkelä",
    title: "Marketing Specialist",
    salary: 3800,
    phone: "045-1237890",
    email: "liisa.makela@example.com",
    animal: "Cat",
    startDate: "2025-01-10",
    location: "Vantaa",
    department: "Marketing",
    skills: ["SEO", "Content Creation", "Social Media"],
  },
  {
    id: 4,
    name: "Olli Koskinen",
    title: "Sales Manager",
    salary: 4700,
    phone: "046-5678901",
    email: "olli.koskinen@example.com",
    animal: "Fox",
    startDate: "2019-06-20",
    location: "Tampere",
    department: "Sales",
    skills: ["Negotiation", "CRM", "Customer Service"],
  },
  {
    id: 5,
    name: "Sanna Nieminen",
    title: "Graphic Designer",
    salary: 3600,
    phone: "044-7890123",
    email: "sanna.nieminen@example.com",
    animal: "Rabbit",
    startDate: "2023-11-01",
    location: "Turku",
    department: "Design",
    skills: ["Photoshop", "Illustrator", "Figma"],
  },
  {
    id: 6,
    name: "Jari Heikkinen",
    title: "Accountant",
    salary: 4000,
    phone: "040-2345678",
    email: "jari.heikkinen@example.com",
    animal: "Bear",
    startDate: "2009-05-12",
    location: "Helsinki",
    department: "Finance",
    skills: ["Accounting", "Excel", "Financial Reporting"],
  },
  {
    id: 7,
    name: "Emma Saarinen",
    title: "Customer Service Representative",
    salary: 3200,
    phone: "050-8765432",
    email: "emma.saarinen@example.com",
    animal: "Panda",
    startDate: "2024-04-01",
    location: "Jyväskylä",
    department: "Customer Support",
    skills: ["Problem Solving", "Empathy", "Conflict Resolution"],
  },
  {
    id: 8,
    name: "Antti Korhonen",
    title: "Project Manager",
    salary: 6000,
    phone: "041-6549873",
    email: "antti.korhonen@example.com",
    animal: "Tiger",
    startDate: "2014-02-20",
    location: "Espoo",
    department: "Operations",
    skills: ["Project Management", "Scrum", "Leadership"],
  },
  {
    id: 9,
    name: "Helena Salmi",
    title: "UX Designer",
    salary: 4700,
    phone: "046-1597534",
    email: "helena.salmi@example.com",
    animal: "Cat",
    startDate: "2020-07-01",
    location: "Oulu",
    department: "Product",
    skills: ["UX Research", "Prototyping", "User Testing"],
  },
  {
    id: 10,
    name: "Ville Aalto",
    title: "Business Analyst",
    salary: 5200,
    phone: "045-8529637",
    email: "ville.aalto@example.com",
    animal: "Fox",
    startDate: "2010-03-05",
    location: "Lahti",
    department: "Business Development",
    skills: ["Data Analysis", "SQL", "Reporting"],
  },
];
